Repository RestTest-App/RestTest_FE, pull requests merged in 2025-06, with the labels that each got.

#15 Feature/onboarding_ui #5 - Create 회원가입 UI
  assets/images/resttest_logo.png
  lib/binding/root_binding.dart
  lib/utility/static/app_pages.dart
  lib/view/onboarding/onboarding_screen.dart
  lib/view/onboarding/onboarding_steps/certificate_step.dart
  lib/view/onboarding/onboarding_steps/nickname_step.dart
  lib/view/onboarding/onboarding_steps/terms_step.dart
  lib/view/onboarding/onboarding_steps/user_info_step.dart
  lib/view/onboarding/terms_page.dart
  lib/viewmodel/onboarding/onboarding_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: 💄style, ✨feature, 👦지원

#25 Feature/review_detail_ui-#23 - 복습노트 디테일 UI 구현
  lib/binding/root_binding.dart
  lib/model/review/ReviewDetailModel.dart
  lib/model/review/ReviewListModel.dart
  lib/utility/static/app_pages.dart
  lib/utility/static/app_routes.dart
  lib/view/review/component/review_detail_item.dart
  lib/view/review/review_content_screen.dart
  lib/view/review/widget/review_exam_item.dart
  lib/view/test/component/exam_result_item.dart
  lib/viewmodel/book/book_view_model.dart
  lib/viewmodel/review/review_view_model.dart
Labels: 💄style, ✨feature, 👩지희

#30 Feature/connect_api-#27 - 마이페이지 api 연결
  assets/images/default_profile.png
  assets/images/profile.png
  lib/binding/init_binding.dart
  lib/binding/root_binding.dart
  lib/provider/auth/auth_provider.dart
  lib/provider/auth/auth_provider_impl.dart
  lib/provider/base/base_connect.dart
  lib/provider/user/user_provider.dart
  lib/provider/user/user_provider_impl.dart
  lib/repository/user/user_repository.dart
  lib/repository/user/user_repository_impl.dart
  lib/utility/static/app_pages.dart
  lib/view/home/home_screen.dart
  lib/view/home/widget/goal_card.dart
  lib/view/mypage/profile_change_screen.dart
  lib/view/mypage/widget/profile_card.dart
  lib/view/mypage/widget/settings_card.dart
  lib/viewmodel/home/home_view_model.dart
  lib/viewmodel/mypage/mypage_view_model.dart
  lib/viewmodel/mypage/profile_change_view_model.dart
  pubspec.yaml
Labels: ✨feature, 👩가흔
